// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

import (
	"time"
)

type APIUsage struct {
	StatusCode int `json:"statusCode"`
	Count      int `json:"count"`
}

type EndpointPerformance struct {
	EndpointID     string  `json:"endpointId"`
	Path           string  `json:"path"`
	Method         string  `json:"method"`
	TotalRequests  int     `json:"totalRequests"`
	AverageLatency float64 `json:"averageLatency"`
	ErrorRate      float64 `json:"errorRate"`
}

type ErrorStatistics struct {
	ErrorCode    string    `json:"errorCode"`
	Count        int       `json:"count"`
	LastOccurred time.Time `json:"lastOccurred"`
}

type Query struct {
}

type ServiceMetrics struct {
	TotalRequests     int     `json:"totalRequests"`
	RequestsPerSecond float64 `json:"requestsPerSecond"`
	AverageLatency    float64 `json:"averageLatency"`
	P95Latency        float64 `json:"p95Latency"`
	P99Latency        float64 `json:"p99Latency"`
	ErrorRate         float64 `json:"errorRate"`
	SuccessRate       float64 `json:"successRate"`
}

type TimeRange struct {
	Start time.Time `json:"start"`
	End   time.Time `json:"end"`
}
